import { createFileRoute } from "@tanstack/react-router";
import { toast } from "sonner";
import { Download, FileJson, FileSpreadsheet, Printer, FileText } from "lucide-react";

export const Route = createFileRoute("/_app/reports")({
  component: ReportsPage,
});

function ReportsPage() {
  return (
    <div className="space-y-6">
      <div className="flex items-end justify-between flex-wrap gap-3">
        <div>
          <h1 className="text-3xl font-semibold tracking-tight">Research Report</h1>
          <p className="text-sm text-muted-foreground mt-1">exp_001 — Vaccination impact on campus flu</p>
        </div>
        <div className="flex flex-wrap gap-2">
          <ActionBtn icon={Download} label="Download PDF" onClick={() => toast.success("PDF downloaded")} primary />
          <ActionBtn icon={FileSpreadsheet} label="CSV" onClick={() => toast.success("CSV downloaded")} />
          <ActionBtn icon={FileJson} label="JSON" onClick={() => toast.success("JSON downloaded")} />
          <ActionBtn icon={Printer} label="Print" onClick={() => window.print()} />
        </div>
      </div>

      <div className="glass rounded-2xl p-2">
        <div className="rounded-xl bg-white text-neutral-900 p-10 min-h-[900px] shadow-inner font-serif">
          <div className="border-b pb-6 border-neutral-200">
            <p className="text-xs uppercase tracking-widest text-neutral-500">EpidemAI Research Report</p>
            <h2 className="text-3xl font-bold mt-2">Vaccination Impact on Influenza Spread within a University Campus</h2>
            <p className="text-neutral-500 mt-2 text-sm">Generated by EpidemAI multi-agent system — July 14, 2026</p>
          </div>
          <section className="mt-8 space-y-4 text-neutral-800 leading-relaxed">
            <h3 className="text-xl font-semibold">Abstract</h3>
            <p className="text-sm">We simulate influenza spread within a synthetic university campus of 10,000 individuals under varying vaccination coverage. Using a SEIR model on a small-world contact graph, we quantify the effect of coverage on peak infection, total attack rate, and time-to-peak.</p>
            <h3 className="text-xl font-semibold">Methods</h3>
            <p className="text-sm">A small-world contact network (k=6, β=0.1) was generated. The SEIR model was parameterised with an incubation period of 3.2 days and infectious period of 6.1 days, yielding R₀ ≈ 2.4. Vaccination reduced individual susceptibility by 70%.</p>
            <h3 className="text-xl font-semibold">Results</h3>
            <p className="text-sm">At 42% coverage, peak infection reached 4,200 individuals on day 20 with a total attack rate of 78.3%. Increasing coverage to 65% suppressed the peak by 61% and delayed it by 9 days.</p>
            <h3 className="text-xl font-semibold">Conclusions</h3>
            <p className="text-sm">Moderate-to-high vaccination coverage substantially reduces peak burden. Contact network topology materially influences outcomes and should be modelled explicitly for campus settings.</p>
            <div className="mt-8 flex items-center gap-2 text-xs text-neutral-500"><FileText className="h-3 w-3" /> Page 1 of 12</div>
          </section>
        </div>
      </div>
    </div>
  );
}

function ActionBtn({ icon: Icon, label, onClick, primary }: { icon: any; label: string; onClick: () => void; primary?: boolean }) {
  return (
    <button onClick={onClick}
      className={`inline-flex items-center gap-2 rounded-xl px-3.5 py-2 text-sm font-medium ${primary ? "gradient-brand text-white glow-brand" : "border border-white/10 bg-white/5 hover:bg-white/10"}`}>
      <Icon className="h-4 w-4" /> {label}
    </button>
  );
}
