import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { toast } from "sonner";
import { motion } from "framer-motion";
import { Sparkles, Play, ClipboardList } from "lucide-react";

export const Route = createFileRoute("/_app/research")({
  component: Research,
});

function Research() {
  const [prompt, setPrompt] = useState("");
  const [disease, setDisease] = useState("Influenza");
  const [model, setModel] = useState("Auto");
  const [pop, setPop] = useState(10000);
  const [days, setDays] = useState(60);
  const [network, setNetwork] = useState("Small World");

  return (
    <div className="space-y-6 max-w-4xl mx-auto">
      <div>
        <h1 className="text-3xl font-semibold tracking-tight">New Research</h1>
        <p className="text-sm text-muted-foreground mt-1">Describe your question. Agents will plan and execute the experiment.</p>
      </div>

      <motion.div initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} className="glass rounded-3xl p-6">
        <label className="text-xs uppercase tracking-wider text-muted-foreground flex items-center gap-2">
          <Sparkles className="h-3.5 w-3.5 text-[color:var(--brand-2)]" /> Research Prompt
        </label>
        <textarea
          value={prompt} onChange={e => setPrompt(e.target.value)}
          rows={4}
          placeholder="How does vaccination affect influenza spread in a university campus?"
          className="mt-2 w-full bg-white/5 border border-white/10 rounded-2xl p-4 outline-none focus:border-[color:var(--brand)]/50 resize-none"
        />

        <div className="mt-6 grid md:grid-cols-2 gap-4">
          <Field label="Disease">
            <Select value={disease} onValueChange={setDisease}>
              <SelectTrigger><SelectValue /></SelectTrigger>
              <SelectContent>
                {["COVID", "Influenza", "Dengue", "Ebola", "Custom"].map(d => <SelectItem key={d} value={d}>{d}</SelectItem>)}
              </SelectContent>
            </Select>
          </Field>
          <Field label="Model">
            <Select value={model} onValueChange={setModel}>
              <SelectTrigger><SelectValue /></SelectTrigger>
              <SelectContent>
                {["Auto", "SIR", "SEIR", "SIS"].map(d => <SelectItem key={d} value={d}>{d}</SelectItem>)}
              </SelectContent>
            </Select>
          </Field>
          <Field label="Population Size">
            <input type="number" value={pop} onChange={e => setPop(Number(e.target.value))}
              className="w-full bg-white/5 border border-white/10 rounded-xl px-3 py-2 text-sm outline-none focus:border-[color:var(--brand)]/50" />
          </Field>
          <Field label="Simulation Days">
            <input type="number" value={days} onChange={e => setDays(Number(e.target.value))}
              className="w-full bg-white/5 border border-white/10 rounded-xl px-3 py-2 text-sm outline-none focus:border-[color:var(--brand)]/50" />
          </Field>
          <Field label="Contact Network">
            <Select value={network} onValueChange={setNetwork}>
              <SelectTrigger><SelectValue /></SelectTrigger>
              <SelectContent>
                {["Random", "Scale-Free", "Small World", "Complete Graph"].map(d => <SelectItem key={d} value={d}>{d}</SelectItem>)}
              </SelectContent>
            </Select>
          </Field>
        </div>

        <div className="mt-6 flex flex-wrap gap-3">
          <button onClick={() => toast.success("Plan generated by Discovery Scientist")}
            className="inline-flex items-center gap-2 rounded-xl border border-white/10 bg-white/5 hover:bg-white/10 px-4 py-2.5 text-sm font-medium">
            <ClipboardList className="h-4 w-4" /> Generate Plan
          </button>
          <button onClick={() => toast.success("Experiment queued — 13 agents assigned")}
            className="inline-flex items-center gap-2 gradient-brand text-white rounded-xl px-4 py-2.5 text-sm font-medium glow-brand">
            <Play className="h-4 w-4" /> Run Experiment
          </button>
        </div>
      </motion.div>
    </div>
  );
}

function Field({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <div>
      <label className="text-xs uppercase tracking-wider text-muted-foreground">{label}</label>
      <div className="mt-1.5">{children}</div>
    </div>
  );
}
